#!/bin/bash

# 🔑 Enable SSH Password Authentication on VK Cloud
# This script helps you enable password authentication if you have any access method

echo "🔑 VK Cloud SSH Access Solutions"
echo "================================"

echo ""
echo "Option 1: VK Cloud Web Console"
echo "------------------------------"
echo "1. Go to: https://mcs.mail.ru/app/services/infra/servers/"
echo "2. Find your server (95.163.180.91)"
echo "3. Click on the server name"
echo "4. Click 'Console' or 'VNC Console' button"
echo "5. Login with root and your password"
echo "6. Run these commands:"
echo ""
echo "   sed -i 's/#PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config"
echo "   sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config"
echo "   systemctl restart sshd"
echo ""

echo "Option 2: VK Cloud API (if you have API access)"
echo "-----------------------------------------------"
echo "You can use VK Cloud API to run commands remotely"
echo ""

echo "Option 3: Recovery Mode"
echo "----------------------"
echo "1. Go to VK Cloud Console"
echo "2. Stop your server"
echo "3. Boot in recovery mode"
echo "4. Mount your disk and edit SSH config"
echo ""

echo "Option 4: Create New SSH Key"
echo "---------------------------"
echo "1. Generate new SSH key:"
echo "   ssh-keygen -t rsa -b 4096 -f ~/.ssh/vk_cloud_key"
echo ""
echo "2. Add public key to VK Cloud:"
echo "   - Go to VK Cloud Console → Compute → Key Pairs"
echo "   - Click 'Add Key Pair'"
echo "   - Copy content of ~/.ssh/vk_cloud_key.pub"
echo "   - Assign to your server"
echo ""
echo "3. Connect with new key:"
echo "   ssh -i ~/.ssh/vk_cloud_key root@95.163.180.91"
echo ""

echo "Option 5: Contact VK Cloud Support"
echo "----------------------------------"
echo "If none of the above work, contact VK Cloud support:"
echo "- Email: support@mcs.mail.ru"
echo "- Phone: +7 (495) 933-99-00"
echo "- Ask them to reset SSH access or enable password authentication"
echo ""

echo "🚀 Quick Test After Enabling Password Auth:"
echo "ssh root@95.163.180.91"
echo ""
echo "If successful, you can then run the email server setup:"
echo "scp setup-email-server.sh root@95.163.180.91:/root/"
echo "ssh root@95.163.180.91"
echo "./setup-email-server.sh"
